port: 9000
jwt:
  expiration_in_minutes: 14400
  secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
mongodb:
  database: users
  connection_string: mongodb+srv://admin:admin@users.ssocs.mongodb.net/?ssl=false